import React from 'react'
import ReactDOM from 'react-dom'
import Container from '../prototypes/prototype_6/Container'

const fonts = [
  'Alegreya Sans SC, sans-serif',
  'Alegreya SC, serif',
  'Amatic SC, cursive',
  'Andika, sans-serif',
  'Anonymous Pro, monospace',
  'Arimo, sans-serif',
  'Arsenal, sans-serif',
  'Balsamiq Sans, cursive',
  'Bellota Text, cursive',
  'Bitter, serif',
  'Caveat, cursive',
  'Comfortaa, cursive',
  'Commissioner, sans-serif',
  'Cormorant, serif',
  'Cormorant Garamond, serif',
  'Cormorant Infant, serif',
  'Cormorant SC, serif',
  'Cousine, monospace',
  'Cuprum, sans-serif',
  'Dela Gothic One, cursive',
  'EB Garamond, serif',
  'El Messiri, sans-serif',
  'Exo 2, sans-serif',
  'Fira Code, monospace',
  'Fira Sans, sans-serif',
  'Fira Sans Condensed, sans-serif',
  'Forum, cursive',
  'Gabriela, serif',
  'IBM Plex Sans, sans-serif',
  'IBM Plex Serif, serif',
  'Inter, sans-serif',
  'Istok Web, sans-serif',
  'JetBrains Mono, monospace',
  'Jost, sans-serif',
  'Jura, sans-serif',
  'Kelly Slab, cursive',
  'Kiwi Maru, serif',
  'Kosugi Maru, sans-serif',
  'Kurale, serif',
  'Ledger, serif',
  'Literata, serif',
  'Lobster, cursive',
  'Lora, serif',
  'Manrope, sans-serif',
  'Marmelad, sans-serif',
  'Merriweather, serif',
  'Montserrat, sans-serif',
  'Montserrat Alternates, sans-serif',
  'Mulish, sans-serif',
  'Noto Sans Display, sans-serif',
  'Noto Serif, serif',
  'Nunito, sans-serif',
  'Nunito Sans, sans-serif',
  'Oi, cursive',
  'Old Standard TT, serif',
  'Open Sans, sans-serif',
  'Oranienbaum, serif',
  'Orelega One, cursive',
  'Oswald, sans-serif',
  'Overpass, sans-serif',
  'Overpass Mono, monospace',
  'Pacifico, cursive',
  'Pangolin, cursive',
  'Pattaya, sans-serif',
  'Philosopher, sans-serif',
  'Play, sans-serif',
  'Playfair Display, serif',
  'Playfair Display SC, serif',
  'Podkova, serif',
  'Prata, serif',
  'Press Start 2P, cursive',
  'Prosto One, cursive',
  'PT Sans, sans-serif',
  'PT Sans Caption, sans-serif',
  'PT Sans Narrow, sans-serif',
  'PT Serif, serif',
  'Reggae One, cursive',
  'Roboto, sans-serif',
  'Roboto Condensed, sans-serif',
  'Roboto Mono, monospace',
  'Roboto Slab, serif',
  'RocknRoll One, sans-serif',
  'Rubik, sans-serif',
  'Rubik Mono One, sans-serif',
  'Ruslan Display, cursive',
  'Scada, sans-serif',
  'Seymour One, sans-serif',
  'Source Code Pro, monospace',
  'Source Sans 3, sans-serif',
  'Source Sans Pro, sans-serif',
  'Source Serif 4, sans-serif',
  'Source Serif Pro, serif',
  'Spectral, serif',
  'Spectral SC, serif',
  'Stalinist One, cursive',
  'STIX Two Text, serif',
  'Ubuntu, sans-serif',
  'Ubuntu Mono, monospace',
  'Vollkorn, serif',
  'Vollkorn SC, serif',
  'Yanone Kaffeesatz, sans-serif',
  'Yeseva One, cursive',
  'Zen Antique Soft, serif'
]
const fontSize = 64
document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <Container fonts={fonts} fontSize={fontSize} />,
    document.getElementsByClassName('prototype_6')[0]
  )
})
